# Generated by Django 5.2 on 2025-07-03 19:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mockgen', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SourceDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Original file name', max_length=255)),
                ('doc_type', models.CharField(choices=[('PDF', 'PDF Document'), ('PPT', 'PowerPoint Slides'), ('DOC', 'Word Document'), ('IMG', 'Scanned Image')], max_length=10)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('processed', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, help_text='Optional comments or parse issues')),
                ('file', models.FileField(help_text='Upload the original document here', upload_to='source_docs/%Y/%m/%d/')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='source',
            field=models.ForeignKey(blank=True, help_text='The document this question was extracted from', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='questions', to='mockgen.sourcedocument'),
        ),
    ]
